### ISSUE TITLE
Terminology/Classification services

### ISSUE THREAD

**Issue by tony-shannon** [AppertaFoundation/Code4Health-Platform#11]
Standards
SNOMED CT
ICD-10

Examples
https://github.com/wardle/rsterminology
http://www.apelondts.org/

Discuss/Debate/Action

**Comment by Matt-Interneuron** [comment]
Is ApelonDTS an option for terminology services on C4H platform?

**Comment by tony-shannon** [comment]
thanks @Matt-Interneuron 
Meant to include it as example, as its the reference tech for that component in the ohie.org work
I've now added it

We need to identify the component parts and then work out plan of pulling together into a coherent ensemble (Marcus will suggest a Docker compose I think)

**Comment by tony-shannon** [comment]
moving this issue to https://github.com/AppertaFoundation/apperta-issues/issues/15
