### ISSUE TITLE
Code4Health-Platform  repo purpose?

### ISSUE THREAD

**Issue by tony-shannon** [AppertaFoundation/Code4Health-Platform#18]
Can we please clarify /confirm what the purpose of this repo is?

It has code in it for deploying instances of an Operino

We discussed at recent session on need to separate out aspects of the Code4Health push into
-community building 
-open platform component building
-get up and running tooling building

**Comment by robdyke** [comment]
@tony-shannon this repo has the 'portal' code which is running on platform.code4health.org ... confusingly

Had mentioned in a round-about-way #1 

Expect this repo to be renamed / archived in near future
