### ISSUE TITLE
Forgot password functionality doesn't seem to work

### ISSUE THREAD

**Issue by Matt-Interneuron** [AppertaFoundation/Code4Health-Platform#19]
I've attempted multiple times to reset my password using the Forgot Password link on the sign-page to the platform, but I do not get any emails with how to reset my password.

I know the email address is correct as it will not let me re-register it.

**Comment by Fishy1976** [comment]
@robdyke could you investigate please?

**Comment by robdyke** [comment]
@Matt-Interneuron Sorry the forgot password function isn't working. This problem was reported to @AppertaFoundation/inidus-team earlier today and is being investigated.
